name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Contructores Herencia
      id: test-contructores-herencia
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 50
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CONTRUCTORES-HERENCIA_RESULTS: "${{steps.test-contructores-herencia.outputs.result}}"
      with:
        runners: test-contructores-herencia
